on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
        -  mathcomp/mathcomp:1.14.0-coq-8.13
        -  mathcomp/mathcomp:1.14.0-coq-8.14
        -  mathcomp/mathcomp:1.14.0-coq-8.15
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        custom_image: ${{ matrix.image }}
